openapi: 3.0.3
info:
  title: Project API
  version: 1.0.0
  description: |
    Before creating a new project and registering its public key

    1. Generate RSA private key `openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:4096`
    2. Extract the public key `openssl rsa -pubout -in private_key.pem -out public_key.pem`
    3. Get the public key's content as a single string with `awk '{printf "%s\\n", $0}' public_key.pem | sed 's/\\n$//'`

tags:
  - name: projects
    description: Things people work on
  - name: keys
    description: Public keys of projects

servers:
  - url: http://127.0.0.1:{port}
    description: Local development server
    variables:
      port:
        default: "5000"
        enum:
          - "5000"
          - "8080"
          - "3000"

paths:
  /projects:
    post:
      summary: Create a new project with a public key
      tags:
        - projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
                  example: "Demo project name"
                public_key:
                  type: string
                  pattern: '^-----BEGIN PUBLIC KEY-----[\\s\\S]*-----END PUBLIC KEY-----$'
                  description: The public key in PEM format.
                  example: |
                    -----BEGIN PUBLIC KEY-----
                    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArjs/EcBLWLXMB9PiOgal
                    ZMvP05T2zq6aksf+hQrZoSsVOeuIdr8JC6fbBrQeXKzfxSU39TdgLG16I4dgyMpP
                    hwPpyapbU79mqZ6Edxi9WrqspUaks8A9s/BPiTN31nTOoFKydRHO6NXXPmkLHRgG
                    3GFcEYr0KRT+Aj7LGPDZeFSC4zX5vBl6nUo1J4B0YNdu0CSO0JoUfjZ6YOaZngK1
                    0JmiwxAcuR7CaouyfmML2b2qRP0qRckL/afxRXsUx5bdiw6swbVIt4W0K4/7Hjw7
                    X30ALE3m1pnkfTd5nC2szPWZaAWVv+XRzHgwjtzdXQVw/sx3sHvjs7SuEd+uS/7C
                    QxtMxEeS4EI2+d+w6jKRk1Cbv5abFp+gzngMzbmdOr3aIibT6QkqUgsz/9X0gQ7b
                    92Gl7hPDgyGgZYoi3kJRuQsKCyEfJipe1g4QBMv+iYkR67l1geTjDPrnGQz5GSC+
                    ojcsFXecJtBFgU3Mw4LtvP7ZEwhn+DjMpQZ7RjenNxAep86CcyT/TdT1mRH1nCZo
                    2IoCD9xcM0sgtWtxJeicxJ7qRjUvTrmTlSd2+kef0Ycb2kCwTB7iCrgIEhYdt2CF
                    HfNBHMMVduJf/RTV0cPXf041cLyHYEzpZnrQ4FWcXLoBWjzGmiaT+TggiyEkro0j
                    HR57xlAN43ucGD3PtjwJaOcCAwEAAQ==
                    -----END PUBLIC KEY-----
              required:
                - name
                - public_key
      responses:
        "201":
          description: Project created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  kid:
                    type: string
                    format: uuid
                    description: "The registered id of the public key"
                    example: "721a0653-413a-4f88-9700-a12f1dea355f"
                  project:
                    $ref: "#/components/schemas/Project"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorGroup"
    get:
      summary: Read a project
      tags:
        - projects
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Project retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  project:
                    $ref: "#/components/schemas/Project"
        "404":
          description: Project not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorGroup"
    delete:
      summary: Delete a project
      tags:
        - projects
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Project deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  project:
                    $ref: "#/components/schemas/Project"
        "404":
          description: Project not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorGroup"

  /keys:
    post:
      summary: Create a new key for a project
      tags:
        - keys
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                public_key:
                  type: string
              required:
                - public_key
      responses:
        "201":
          description: Key created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  kid:
                    type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorGroup"
        "404":
          description: Project not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorGroup"
    get:
      summary: Read keys of the project
      tags:
        - keys
      security:
        - bearerAuth: []
      parameters:
        - name: page_size
          description: |
            The amount of keys to fetch at a time.
            Either page size or page token must be provided.
          in: query
          schema:
            type: integer
        - name: page_token
          description: |
            The encoded info for loading next page of keys.
            Either page size or page token must be provided.
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Keys retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  keys:
                    type: array
                    items:
                      type: object
                      properties:
                        created_at:
                          type: string
                          format: date-time
                          description: The timestamp when the key was created
                        id:
                          type: string
                          format: uuid
                          description: The unique identifier for the key
                        pem:
                          type: string
                          description: The public key in PEM format
                        project_id:
                          type: string
                          format: uuid
                          description: The unique identifier for the project associated with the key
                  next_page_token:
                    type: string
                    nullable: true
                    description: A token for the next page of results; null if no next page exists
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorGroup"
  /keys/{id}:
    delete:
      summary: Delete a key
      security:
        - bearerAuth: []
      tags:
        - keys
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Key deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  kid:
                    type: string
        "404":
          description: Public key not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorGroup"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        The Bearer token can be created using the following steps.

        ```bash
        # Install pip dependency
        pip install "PyJWT[crypto]"
        ```

        Create a Python file
        ```python
        from datetime import UTC, datetime, timedelta
        from pathlib import Path
        from uuid import UUID

        import jwt

        if __name__ == "__main__":
            pem = input("Enter path of private PEM file: ")

            with Path(pem).open() as pem_file:
                key_bytes = pem_file.read()
                private_key = key_bytes

            project_id = UUID(input("Enter project id: "))
            public_key_id = UUID(input("Enter public key id (kid): "))

            print(  # noqa: T201
                jwt.encode(
                    payload={
                        "iat": datetime.now(tz=UTC),
                        "exp": datetime.now(tz=UTC) + timedelta(minutes=5),
                        "iss": str(project_id),
                    },
                    key=private_key,
                    algorithm="RS256",
                    headers={"kid": str(public_key_id)},
                ),
            )

        ```

        Run the Python file using your private key PEM location, project id and the corresponding public key's ID returned by the API after registering the public key.

        ```bash
        python3 your_file_name.py
        ```

        Use the obtained bearer value for authorization.
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
    ErrorGroup:
      type: object
      properties:
        status:
          type: string
        errors:
          type: array
          items:
            $ref: "#/components/schemas/Error"
    Project:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "18c64064-b83e-45b6-ba68-ef681d06bb09"
        name:
          type: string
          example: "Demo project name"
